### ISSUE TITLE
Why are header values arrays?

### ISSUE THREAD

**Issue by ostrolucky** [Mapudo/guzzle-bundle#18]
![screenshot from 2018-01-07 00-22-26](https://user-images.githubusercontent.com/496233/34644919-ddf4e296-f340-11e7-8a36-4b50be146bc8.png)

**Comment by kobelobster** [comment]
Hey @ostrolucky 

This is due to PSR-7 and it's requirements to support headers that have multiple values. Since our library depends on guzzle, which follows the PSR-7 standard it has to be that way.

See here: http://www.php-fig.org/psr/psr-7/#headers-with-multiple-values

Relevant paragraph:
> In order to accommodate headers with multiple values yet still provide the convenience of working with headers as strings, headers can be retrieved from an instance of a MessageInterface as an array or a string. Use the getHeaderLine() method to retrieve a header value as a string containing all header values of a case-insensitive header by name concatenated with a comma. Use getHeader() to retrieve an array of all the header values for a particular case-insensitive header by name.

As you can read, to get the value as a single string, just use `getHeaderLine('Accept-Language')` for example.
  
If you've got further questions: Just reopen it.

**Comment by ostrolucky** [comment]
Oh... Sorry for not being specific enough. The screenshot I pasted is actually directly from your profiler screen. I believe it shouldn't be like that?

**Comment by kobelobster** [comment]
Seems like we have a little misunderstanding here. Could you tell me what you would expect here? Are you talking about the header in general or about the values of a header, i.e. why the value of `Host` is an array?

Currently it's expected to look like this, because it's a simple debug information and we can just pass this array into the `dump` method of Symfony so you can open it through the arrows, etc.

**Comment by ostrolucky** [comment]
Here is how it looks in csa/guzzle-bundle

![](https://user-images.githubusercontent.com/496233/34644966-286466c0-f342-11e7-9f4e-35a4156006b1.png)

That's how I would expect headers view in profiler look like. Not hidden behind some arrows. Very bad UX.

**Comment by kobelobster** [comment]
Ah, now I see what you were talking about. Yes indeed, that is better than the current implementation. :smile:, however this is a feature request which has a low priority. I opened an issue in our tracking system, but I can't promise you that we'll fix this in the near future.

If you want this feature and need it, feel free to open a PR :+1: 
 
Note to self: Issue number in tracking system is: MAP-2294

**Comment by ostrolucky** [comment]
Nah, I don't even use this bundle. Was just evaluating it and decided it would be nice if I report my findings to you.

**Comment by kobelobster** [comment]
Alright! Thank you for reporting this issue and I'll close it again
